#include <cinttypes>
#include <atomic>

#include "incr.h"

using namespace std;


atomic<uint64_t> X;
atomic<uint64_t> Y;

void incr(uint64_t n) {
  for (uint64_t i = 0; i < n; i++) {
    X.fetch_add(1, memory_order_relaxed);
  }
}

void incr_load(uint64_t n) {
  for (uint64_t i = 0; i < n; i++) {
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
  }
}

void incr_store(uint64_t n) {
  for (uint64_t i = 0; i < n; i++) {
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
  }
}

uint64_t xchg(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i++) {
    sum += X.exchange(i, memory_order_relaxed);
  }
  return sum;
}

uint64_t xchg_load(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i++) {
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
  }
  return sum;
}

uint64_t xchg_store(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i++) {
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
  }
  return sum;
}

uint64_t load(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i+=4) {
    sum += X.load(memory_order_relaxed);
  }
  return sum;
}

uint64_t load_store(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i+=4) {
    sum += X.load(memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
  }
  return sum;
}

uint64_t load_unroll(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i+=4) {
    sum += X.load(memory_order_relaxed);
    sum += X.load(memory_order_relaxed);
    sum += X.load(memory_order_relaxed);
    sum += X.load(memory_order_relaxed);
  }
  return sum;
}

uint64_t load_store_unroll(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i+=4) {
    sum += X.load(memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.load(memory_order_relaxed);
    Y.store(i + 1, memory_order_relaxed);
    sum += X.load(memory_order_relaxed);
    Y.store(i + 2, memory_order_relaxed);
    sum += X.load(memory_order_relaxed);
    Y.store(i + 3, memory_order_relaxed);
  }
  return sum;
}


/** incr/xchg unrolled */

void incr_unroll(uint64_t n) {
  for (uint64_t i = 0; i < n; i+=100) {
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
  }
}

void incr_load_unroll(uint64_t n) {
  for (uint64_t i = 0; i < n; i+=100) {
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.load(memory_order_relaxed);
  }
}

void incr_store_unroll(uint64_t n) {
  for (uint64_t i = 0; i < n; i+=100) {
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    X.fetch_add(1, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
  }
}

uint64_t xchg_unroll(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i+=100) {
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
  }
  return sum;
}

uint64_t xchg_load_unroll(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i+=100) {
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.load(memory_order_relaxed);
  }
  return sum;
}

uint64_t xchg_store_unroll(uint64_t n) {
  uint64_t sum = 0;
  for (uint64_t i = 0; i < n; i+=100) {
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
    sum += X.exchange(i, memory_order_relaxed);
    Y.store(i, memory_order_relaxed);
  }
  return sum;
}
